# Generated by Django 2.1.3 on 2018-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('url', models.URLField()),
                ('read', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
