# Generated by Django 2.1.3 on 2018-12-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
