# Generated by Django 2.0.9 on 2018-12-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeed', '0003_auto_20181211_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['-hit']},
        ),
    ]
